[DEFAULT]
upstream-branch = master
debian-branch = ubuntu/questing
upstream-tag = v%(version)s

[buildpackage]
ignore-new = true
pbuilder = true
dist = questing
submodules = true


[pq]
ignore-new=true
