[DEFAULT]
upstream-branch = master
debian-branch = ubuntu/oracular
upstream-tag = v%(version)s

[buildpackage]
ignore-new = true
pbuilder = true
dist = oracular
submodules = true


[pq]
ignore-new=true
